#!/bin/sh

nix-shell "$(dirname "$0")/../shell.nix" --run 'while true; do cabal run frontend & pid="$!"; trap "kill $pid; exit" 1 2 3 6 9 15; inotifywait -e modify,create,delete -r common frontend && kill "$pid" && sleep 2; done'
