#!/bin/sh

dir="$(dirname "$0")"
[ -z "$IN_NIX_SHELL" ] && exec nix-shell "$dir/../shell.nix" --run "$(readlink -f "$0")"

while true; do
  "$dir/static"
  "$dir/frontend.jsexe"
  "$dir/backend"
  trap "pkill backend; exit" 9 15

  "$dir/wait" && pkill backend
  sleep 2
done
