#!/bin/sh

dir="$(dirname "$0")"
[ -z "$IN_NIX_SHELL" ] && exec nix-shell "$dir/../shell.nix" --run "$(readlink -f "$0")"

rm -rf static/out
cabal run obelisk-asset-manifest-generate "$(nix-build static --no-out-link)" static/manifest obelisk-generated-static Obelisk.Generated.Static static/out
"$dir/mkAssets" "static/out" "static.assets"
